.TH INXI 1 "2015\-08\-20" inxi "inxi manual"
.SH NAME
inxi  \- Command line system information script for console and IRC 
.SH SYNOPSIS
.B inxi \fR \- Single line, short form. Very basic output.

.B inxi \fR[\fB\-AbCdDfFGhHiIlmMnNopPrRsSuw\fR]  \fR[\fB\-c  NUMBER\fR] \fR[\fB\-v  NUMBER\fR]

.B inxi  \fR[\fB\-t \fR(\fBc\fR or\fB m\fR or\fB cm\fR or\fB mc NUMBER\fR)] \fR[\fB\-x \-OPTION\fR(\fBs\fR)] \fR[\fB\-xx \-OPTION\fR(\fBs\fR)] \fR[\fB\-xxx \-OPTION\fR(\fBs\fR)]

.B inxi \fR[\fB\-\-help\fR] \fR[\fB\-\-recommends\fR] \fR[\fB\-\-version\fR] \fR[\fB\-@ NUMBER\fR] 
.SH DESCRIPTION
.B inxi\fR is a command line system information script built for for console and IRC. It is also used for forum technical support, as a debugging tool, to quickly ascertain user system configuration and hardware. inxi shows system 
hardware, CPU, drivers, Xorg, Desktop, Kernel, GCC version(s), Processes, RAM usage, and a wide variety of other 
useful information. 
.B inxi\fR output varies between CLI and IRC, with some default filters and color options applied to IRC use. Script colors can
be turned off if desired with \fB\-c 0\fR, or changed using the \fB\-c\fR color options listed in the OPTIONS section below.
.SH PRIVACY AND SECURITY
In order to maintain basic privacy and security, inxi filters out automatically on IRC things like
your network card mac address, WAN and LAN IP, your \fB/home\fR username directory in partitions, 
and a few other things.

Because inxi is often used on forums for support, you can also trigger this filtering with the \fB\-z\fR
option (\fB\-Fz\fR, for example). To override the IRC filter, you can use the \fB\-Z\fR option. This can be useful 
to debug network connection issues online in a private chat, for example.
.SH USING OPTIONS
Options can be combined if they do not conflict. Either group the letters 
together or separate them.

Letters with numbers can have no gap or a gap at your discretion unless using \fB \-t\fR.

For example: 

.B inxi \-AG\fR or \fBinxi \-A \-G\fR or \fBinxi \-c10
.SH STANDARD OPTIONS 
.TP
.B \-A  
Show Audio/sound card information.
.TP
.B \-b  
Shows basic output, short form (previously \fB\-d\fR). Same as: \fBinxi \-v 2
.TP
.B \-c \fR[\fB0\fR\-\fB32\fR] 
Available color schemes. Scheme number is required. 
  
Supported color schemes: \fB0\-32
.TP	 
.B \-c \fR[\fB94\fR\-\fB99\fR]
Color selectors run a color selector option  prior to inxi starting which lets 
you set the config file value for the selection.

Color selectors for each type display (NOTE: irc and global only show safe color set):
.TP
.B \-c 94\fR
\- Console, out of X.
.TP
.B \-c 95\fR
\- Terminal, running in X \- like xTerm.
.TP
.B \-c 96\fR
\- Gui IRC, running in X \- like Xchat, Quassel, 
Konversation etc.
.TP
.B \-c 97\fR
\- Console IRC running in X \- like irssi in xTerm.
.TP
.B \-c 98\fR
\- Console IRC not in  X.
.TP
.B \-c 99\fR
\- Global \- Overrides/removes all settings.

Setting specific color type removes the global color selection.
.TP
.B \-C  
Show full CPU output, including per CPU clockspeed and CPU max speed (if available). If max speed data
present, shows \fB(max)\fR in short output formats (\fB\inxi\fR, \fB\inxi \-b\fR) if CPU actual speed 
matches CPU max speed. If CPU max speed does not match CPU actual speed, shows both actual and max speed
information. See \fB\-x\fR and \fB\-xx\fR for more options. 
.TP
.B \-d  
Shows optical drive data. Same as \fB\-Dd\fR. With \fB\-x\fR, adds features line to output. 
\fB\-xx\fR adds a few more features.
.TP
.B \-D  
Show full hard Disk info, not only model, ie: \fB/dev/sda ST380817AS 80.0GB\fR. Shows disk space 
total + used percentage.  The disk used percentage includes space used by swap partition(s), since 
those are not usable for data storage. Note that with RAID disks, the percentage will be wrong
since the total is computed from the disk sizes, but the used is computed from mounted partition used
percentages. This small defect may get corrected in the future. Also, unmounted partitions are not
counted in disk use percentages since inxi has no access to that data.
.TP
.B \-f  
Show all cpu flags used, not just the short list. Not shown with \fB\-F\fR to avoid 
spamming. ARM cpus: show \fBfeatures\fR items.
.TP
.B \-F  
Show Full output for inxi. Includes all Upper Case line letters, plus \fB\-s\fR and \fB\-n\fR.
Does not show extra verbose options like \fB\-d \-f \-l \-m \-o \-p \-r \-t \-u \-x\fR unless you use 
those arguments in the command, like: \fBinxi \-Frmxx\fR
.TP
.B \-G  
Show Graphic card information. Card(s), Display Server (vendor and version number), for example: 
\fBDisplay Server: Xorg 1.15.1 \fR
,screen resolution(s), glx renderer, version). At some point Wayland and other display servers
may be added once enough data has been collected.
.TP
.B \-h
The help menu. Features dynamic sizing to fit into terminal window. Set script global \fBCOLS_MAX_CONSOLE\fR
if you want a different default value, or use \fB-y <width>\fR to temporarily override the defaults or actual window width.
.TP
.B \-\-help
Same as \fB\-h\fR
.TP
.B \-H
The help menu, plus developer options. Do not use dev options in normal 
operation!
.TP
.B \-i  
Show Wan IP address, and shows local interfaces (requires ifconfig network tool). 
Same as \-Nni. Not shown with \fB\-F\fR for user security reasons, you shouldn't 
paste your local/wan IP.
.TP
.B \-I  
Show Information: processes, uptime, memory, irc client (or shell type if run in shell, not irc), inxi version.  
See \fB\-x\fR and \fB\-xx\fR for extra information (init type/version, runlevel).
.TP
.B \-l  
Show partition labels. Default: short partition \fB\-P\fR. For full \fB\-p\fR output, use: \fB\-pl\fR (or \fB\-plu\fR).
.TP
.B \-m  
Memory (RAM) data. Does not show with  \fB\-b\fR or  \fB\-F\fR unless you use  \fB\-m\fR explicitly. Ordered by system board physical system memory array(s) (\fBArray\-[number] capacity:\fR), and individual memory devices (\fBDevice\-[number]\fR). Physical memory array(s) data shows array capacity, and number of devices supported, and Error Correction information. Devices shows locator data (highly variable in syntax), size, speed, type (eg: \fBtype: DDR3\fR). 

Note that \fB\-m\fR uses \fBdmidecode\fR, which must be run as root (or start \fBinxi\fR with \fBsudo\fR), unless you figure out how to set up sudo to permit dmidecode to read \fB/dev/mem\fR as user. Note that speed will not show if \fBNo Module Installed\fR is found in size. This will also turn off Bus Width data output if it is null. 

Because dmidecode data is extremely unreliable, inxi will try to make best guesses. If you see \fB(check)\fR after capacity number, you should check it for sure with specifications. \fB(est)\fR is slightly more reliable, but you should still check the real specifications before buying ram. Unfortunately there is nothing \fBinxi can do to get truly reliable data about the system ram, maybe one day the kernel devs will put this data into \fB/sys\fR, and make it real data, taken from the actual system, not dmi data. For most people, the data will be right, but a significant percentage of users will have either wron max module size, if present, or max capacity.
.TP
.B \-M  
Show machine data. Motherboard, Bios, and if present, System Builder (Like Lenovo).
Older systems/kernels without the required \fB/sys\fR data can use dmidecode instead, run as root. If using dmidecode,
may also show bios revision as well as version. \fB\-! 33\fR can force use of \fBdmidecode\fR data instead of \fB/sys\fR.
.TP
.B \-n  
Show Advanced Network card information. Same as \fB\-Nn\fR. Shows interface, speed, 
mac id, state, etc.
.TP
.B \-N  
Show Network card information. With \fB\-x\fR, shows PCI BusID, Port number.
.TP
.B \-o  
Show unmounted partition information (includes UUID and LABEL if available).
Shows file system type if you have \fBfile\fR installed, if you are root OR if you have
added to \fB/etc/sudoers\fR (sudo v. 1.7 or newer): 

.B <username> ALL = NOPASSWD: /usr/bin/file (sample)

Does not show components (partitions that create the md raid array) of md\-raid arrays.
.TP
.B \-p  
Show full partition information (\fB\-P\fR plus all other detected partitions).
.TP
.B \-P  
Show Partition information (shows what \fB\-v 4\fR would show, but without extra data).
Shows, if detected: \fB/ /boot /home /tmp /usr /var\fR. Use \fB\-p\fR to see all mounted partitions.
.TP
.B \-r  
Show distro repository data. Currently supported repo types:

\fBAPT\fR (Debian, Ubuntu + derived versions)

\fBPACMAN\fR (Arch Linux + derived versions)

\fBPISI\fR (Pardus + derived versions)

\fBPORTAGE\fR (Gentoo, Sabayon + derived versions)

\fBPORTS\fR (OpenBSD, FreeBSD, NetBSD + derived OS types)

\fBSLACKPKG\fR (Slackware + derived versions)

\fBURPMQ\fR (Mandriva, Mageia + derived versions)

\fBYUM/ZYPP\fR (Fedora, Redhat, maybe Suse + derived versions)

(as distro data is collected more will be added. If your's is missing please show us how to get this 
information and we'll try to add it.)
.TP
.B \-R
Show RAID data. Shows RAID devices, states, levels, and components, and extra data with \fB\-x\fR / \fB\-xx\fR. 
md\-raid: If device is resyncing, shows resync progress line as well. 
.TP
.B \-\-recommends   
Checks inxi application dependencies + recommends, and directories, then shows
what package(s) you need to install to add support for that feature.
.TP
.B \-s
Show sensors output (if sensors installed/configured): mobo/cpu/gpu temp; detected 
fan speeds. Gpu temp only for Fglrx/Nvidia drivers. Nvidia shows screen number for > 1 screens.
.TP
.B \-S  
Show System information: host name, kernel, desktop environment (if in X), distro. With \fB\-xx\fR show
dm \- or startx \- (only shows if present and running if out of X), and if in X, with \fB\-xxx\fR show more desktop info, like shell/panel etc.
.TP
.B \-t \fR[\fBc\fR or\fB m\fR or\fB cm\fR or\fB mc NUMBER\fR]\fR
Show processes. If followed by numbers \fB1\-20\fR, shows that number of processes for each type 
(default: \fB5\fR; if in irc, max: \fB5\fR)

Make sure to have no space between letters and numbers (\fB\-t cm10\fR \- right, \fB\-t cm 10\fR \- wrong).
.TP
.B \-t c\fR
\- cpu only. With \fB\-x\fR, shows also memory for that process on same line.
.TP
.B \-t m\fR
\- memory only. With \fB\-x\fR, shows also cpu for that process on same line. If the \i-I line is not triggered,
will also show the system used/total ram information in the first \fBMemory\fR line of output.
.TP
.B \-t cm\fR
\- cpu+memory. With \fB\-x\fR, shows also cpu or memory for that process on same line.
.TP
.B \-u  
Show partition UUIDs. Default: short partition \fB\-P\fR. For full \fB\-p\fR output, use: \fB\-pu\fR (or \fB\-plu\fR).
.TP
.B \-U
Note \- Maintainer may have disabled this function. 

If inxi \fB\-h\fR has no listing for \fB\-U\fR then its disabled.

Auto\-update script. Note: if you installed as root, you must be root to update, 
otherwise user is fine. Also installs / updates this Man Page to: \fB/usr/share/man/man8\fR
This requires that you be root to write to that directory. 
.TP
.B \-V 
inxi version information. Prints information then exits.
.TP
.B \-\-version
same as \fB\-V\fR
.TP
.B \-v	
Script verbosity levels. Verbosity level number is required. Should not be used with \fB\-b\fR or \fB\-F\fR. 

Supported levels: \fB0\-7\fR Examples :\fB inxi \-v 4 \fR or \fB inxi \-v4\fR
.TP
.B \-v 0 
\- Short output, same as: \fBinxi\fR
.TP
.B \-v 1 
\- Basic verbose, \fB\-S\fR + basic CPU (cores, model, clock speed, and max speed, if available) 
+ \fB\-G\fR + basic Disk + \fB\-I\fR.
.TP
.B \-v 2 
\- Adds networking card (\fB\-N\fR), Machine (\fB\-M\fR) data, and shows basic hard disk data 
(names only). Same as: \fBinxi \-b
.TP
.B \-v 3 
\- Adds advanced CPU (\fB\-C\fR); network (\fB\-n\fR) data; triggers \fB\-x\fR advanced data option.
.TP
.B \-v 4 
\- Adds partition size/filled data (\fB\-P\fR) for (if present):\fB/ /home /var/ /boot\fR
Shows full disk data (\fB\-D\fR)
.TP
.B \-v 5 
\- Adds audio card (\fB\-A\fR); memory/ram (\fB\-m\fR);sensors (\fB\-s\fR), partition label (\fB\-l\fR) and UUID (\fB\-u\fR), short form of 
optical drives.
.TP
.B \-v 6 
\- Adds full partition data (\fB\-p\fR), unmounted partition data (\fB\-o\fR), optical drive data (\fB\-d\fR); 
triggers \fB\-xx\fR extra data option.
.TP
.B \-v 7 
\- Adds network IP data (\fB\-i\fR); triggers \fB\-xxx\fR
.TP
.B \-w  
Adds weather line. Note, this depends on an unreliable api so it may not always be working in the future.
To get weather for an alternate location, use \fB\-W <location_string>\fR. See also \fB\-x\fR, \fB\-xx\fR, \fB\-xxx\fR option.
Please note, your distribution's maintainer may chose to disable this feature, so if \fB\-w\fR or \fB\-W\fR don't work, that's why.
.TP
.B \-W <location_string>
Get weather/time for an alternate location. Accepts postal/zip code, city,state pair, or latitude,longitude.
Note: city/country/state names must not contain spaces. Replace spaces with '\fB+\fR' sign. No spaces around \fB,\fR (comma). 
Use only ascii letters in city/state/country names, sorry. 

Examples: \fB\-W 95623\fR OR \fB\-W Boston,MA\fR OR \fB\-W45.5234,\-122.6762\fR OR \fB\-W new+york,ny\fR
OR \fB\-W bodo,norway\fR.
.TP
.B \-y <integer >= 80>
This is an absolute width override which sets the output line width max. Overrides \fBCOLS_MAX_IRC\fR / \fBCOLS_MAX_CONSOLE\fR globals, or the actual widths of the terminal. If used with \fB\-h\fR or \fB\-c 94-99\fR, put \fB\-y\fR option first or the override will be ignored. Cannot be used with \fB\-\-help\fR/\fB\-\-version\fR/\fB\-\-recommends\fR type long options. Example: \fBinxi \-y 130 \-Fxx\fR
.TP
.B \-z  
Adds security filters for IP addresses, Mac, location (\fB\-w\fR), and user home directory name. Default on for irc clients.
.TP
.B \-Z  
Absolute override for output filters. Useful for debugging networking issues in irc for example.
.SH EXTRA DATA OPTIONS
These options are for long form only, and can be triggered by one or more \fB\-x\fR, like \fB\-xx\fR.
Alternately, the \fB\-v\fR options trigger them in the following way:
\fB\-v 3\fR adds \fB\-x\fR; \fB\-v 6\fR adds \fB\-xx\fR; \fB\-v 7\fR adds \fB\-xxx\fR

These extra data triggers can be useful for getting more in\-depth data on various options.
Can be added to any long form option list, like: \fB\-bxx\fR or \fB\-Sxxx\fR

There are 3 extra data levels: \fB\-x\fR; \fB\-xx\fR; and \fB\-xxx\fR

The following shows which lines / items get extra information with each extra data level.
.TP
.B \-x \-A 
\- Adds version/port(s)/driver version (if available) for each Audio device.
.TP
.B \-x \-A
\- Shows PCI Bus ID/Usb ID number of each Audio device.
.TP 
.B \-x \-C 
\- bogomips on CPU (if available); CPU Flags (short list).
.TP
.B \-x \-d
\- Adds items to features line of optical drive; adds rev version to optical drive.
.TP
.B \-x \-D
\- Hdd temp with disk data if you have hddtemp installed, if you are root OR if you have added to
\fB/etc/sudoers\fR (sudo v. 1.7 or newer): 

.B <username> ALL = NOPASSWD: /usr/sbin/hddtemp (sample)
.TP
.B \-x \-G 
\- Direct rendering status for Graphics (in X).
.TP
.B \-x \-G 
\- (for single gpu, nvidia driver) screen number gpu is running on.
.TP
.B \-x \-G
\- Shows PCI Bus ID/Usb ID number of each Graphics card.
.TP
.B \-x \-i 
\- Show IPv6 as well for LAN interface (IF) devices.
.TP
.B \-x \-I
\- Show current init system (and init rc in some cases, like OpenRC). With \-xx, shows init/rc
version number, if available.
.B \-x \-I
\- Show system GCC, default. With \-xx, also show other installed GCC versions. 
.TP
.B \-x \-I
\- Show current runlevel (not available with all init systems). 
.TP
.B \-x \-I
\- If in shell (not in IRC client, that is), show shell version number (if available).
.TP
.B \-x \-m
\- Shows memory device Part Number (\fBpart:\fR). Useful to order new or replacement memory sticks etc. Usually part numbers are unique, particularly if you use the word \fBmemory\fR in the search as well. With \fB\-xx\fR, shows Serial Number and Manufactorer as well.
.TP
.B \-x \-m
\- If present, shows maximum memory module/device size in the Array line. Only some systems will have this data available.
.TP
.B \-x \-N
\- Adds version/port(s)/driver version (if available) for each Network card;
.TP
.B \-x \-N
\- Shows PCI Bus ID/Usb ID number of each Network card.
.TP
.B \-x \-R 
\- md\-raid: Shows component raid id. Adds second RAID Info line: raid level; report on drives 
(like 5/5); blocks; chunk size; bitmap (if present). Resync line, shows blocks synced/total blocks.

\- zfs\-raid: Shows raid array full size; available size; portion allocated to RAID (ie, not available as storage)."
.TP
.B \-x \-S 
\- Desktop toolkit if available (GNOME/XFCE/KDE only); Kernel gcc version.
.TP
.B \-x \-t 
\- Adds memory use output to cpu (\fB\-xt c\fR), and cpu use to memory (\fB\-xt m\fR). For \fB\-xt c\fR will also show
system Used/Total ram data if \fB\-t m\fR (memory) is not used AND \fB\-I\fR is not triggered.
.TP
.B \-x \-w / \-W
\- Adds wind speed and time zone (\fB\-w\fR only), and makes output go to two lines.
.TP
.B \-xx \-A 
\- Adds vendor:product ID of each Audio device.
.TP
.B \-xx \-C 
\- Shows Minimum CPU speed (if available).
.TP
.B \-xx \-D 
\- Adds disk serial number.
.TP
.B \-xx \-G 
\- Adds vendor:product ID of each Graphics card.
.TP
.B \-xx \-I 
\- Show init type version number (and rc if present).
.TP
.B \-xx \-I 
\- Adds other detected installed gcc versions to primary gcc output (if present).
.TP
.B \-xx \-I
\- Show, if detected, system default runlevel. Supports Systemd/Upstart/Sysvinit type defaults. Note that
not all systemd systems have the default value set, in that case, if present, it will use the data from 
\fB/etc/inittab\fR.
.TP
.B \-xx \-I 
\- Adds parent program (or tty) that started shell, if not IRC client, to shell information.
.TP
.B \-xx \-m
\- Shows memory device Manufacturer and Serial Number.
.TP
.B \-xx \-m
\- Single/double bank memory, if data is found. Note, this may not be 100% right all of the time since it depends on the order that data is found in \fBdmidecode\fR output for \fBtype 6\fR and \fBtype 17\fR.
.TP
.B \-xx \-M 
\- Adds chassis information, if any data for that is available. Also shows BIOS rom size if using dmidecode.
.TP
.B \-xx \-N 
\- Adds vendor:product ID of each Network card.
.TP
.B \-xx \-R
\- md\-raid: Adds superblock (if present); algorythm, U data. Adds system info line (kernel support,  
read ahead, raid events). Adds if present, unused device line.  If device is resyncing, shows 
resync progress line as well.
.TP
.B \-xx \-S 
\- Adds, if run in X, display manager type to Desktop information, if present. If none, shows N/A.
Supports most known display managers, like xdm, gdm, kdm, slim, lightdm, or mdm.
.TP
.B \-xx \-w / \-W
\- Adds humidity and barometric pressure.
.TP
.B \-xx \-@ <11\-14>
\- Automatically uploads debugger data tar.gz file to \fIftp.techpatterns.com\fR.
.TP
.B \-xxx \-m
\- Memory bus width: primary bus width, and if present, total width. eg: bus width: 64 bit (total: 72 bits). Note that total / data widths are mixed up sometimes in dmidecode output, so inxi will take the larger value as total if present. If no total width data is found, then inxi will not show that item.
.TP
.B \-xxx \-m
\- Adds device Type Detail, eg: DDR3 (Synchronous).
.TP
.B \-xxx \-m
\- If present, will add memory module voltage. Only some systems will have this data available.
.TP
.B \-xxx \-S 
\- Adds, if run in X, shell/panel type info to Desktop information, if present. If none, shows nothing.
Supports some current desktop extras like gnome\-panel, lxde\-panel, and others. Added mainly for Mint support.
.TP
.B \-xxx \-w / \-W
\- Adds location (city state country), weather observation time, altitude of system.
If wind chill, heat index, or dew point are available, shows that data as well.
.SH ADVANCED OPTIONS
.TP
.B \-! 31
Turns off hostname in System line. Useful, with \fB\-z\fR, for anonymizing your inxi output for posting on
forums or IRC.
.TP
.B \-! 32
Turns on hostname in System line. Overrides inxi config file value (if set): B_SHOW_HOST='false'.
.TP
.B \-! 33
Force use of \fBdmidecode\fR. This will override \fB/sys\fR data in some lines, like \fB\-M\fR.
.SH DEBUGGING OPTIONS
.TP
.B \-%
Overrides defective or corrupted data.
.TP
.B \-@  
Triggers debugger output. Requires debugging level \fB1\-14\fR (\fB8\-10\fR \- logging of data).
Less than 8 just triggers inxi debugger output on screen.
.TP
.B \-@  \fR[\fB1\fR\-\fB7\fR] 
\- On screen debugger output.
.TP
.B \-@ 8
\- Basic logging. Check \fB/home/yourname/.inxi/inxi*.log 
.TP
.B \-@ 9
\- Full file/sys info logging.
.TP
.B \-@ 10
\- Color logging.
.TP
.B \-@ <11\-14>
The following create a tar.gz file of system data, plus collecting the inxi output to file:
To automatically upload debugger data tar.gz file to \fIftp.techpatterns.com\fR: 

\fBinxi \-xx@ <11\-14>\fR

For alternate ftp upload locations: Example: 

.B inxi \-! \fIftp.yourserver.com/incoming\fB \-xx@ 14\fR
.TP
.B \-@ 11 
\- With data file of xiin read of \fB/sys
.TP
.B \-@ 12 
\- With xorg conf and log data, xrandr, xprop, xdpyinfo, glxinfo etc.
.TP
.B \-@ 13 
\- With data from dev, disks, partitions, etc., plus xiin data file.
.TP
.B \-@ 14 
\- Everything, full data collection.
.SH SUPPORTED IRC CLIENTS  
BitchX, Gaim/Pidgin, ircII, Irssi, Konversation, Kopete, KSirc, KVIrc, Weechat, and Xchat. Plus any others that
are capable of displaying either built in or external script output.
.SH RUNNING IN IRC CLIENT
To trigger inxi output in your IRC client, pick the appropriate method from the list below:
.TP
.B Xchat, irssi \fR(and many other IRC clients)
.B /exec \-o inxi \fR[\fBoptions\fR]
If you leave off the \fB\-o\fR, only you will see the output on your local IRC client.
.TP
.B Konversation
.B /cmd inxi \fR[\fBoptions\fR]
To run inxi in konversation as a native script if your distribution or inxi package did not do this for you, 
create this symbolic link: 

.B ln \-s /usr/local/bin/inxi /usr/share/kde4/apps/konversation/scripts/inxi

If inxi is somewhere else, change the path \fB/usr/local/bin\fR to wherever it is located.

Then you can start inxi directly, like this:

.B /inxi \fR[\fBoptions\fR]
.TP
.B WeeChat
.B NEW: /exec \-o inxi \fR[\fBoptions\fR]

.B OLD: /shell \-o inxi \fR[\fBoptions\fR]

Newer (2014 and later) WeeChats work pretty much the same now as other console IRC
clients, with \fB/exec \-o inxi \fR[\fBoptions\fR]. Also, newer WeeChats have dropped
the \fB\-curses\fR part of their program name, ie: \fBweechat\fR instead of \fBweechat-curses\fR.

Deprecated: 

Before WeeChat can run external scripts like inxi, you need to install the 
weechat\-plugins package. This is automatically installed for Debian users. 
Next, if you don't already have it, you need to install shell.py,
which is a python script. 

In a web browser, Click on the download button at:
.I http://www.weechat.org/scripts/source/stable/shell.py.html/

Make the script executable by

.B chmod +x shell.py

Move it to your home folder: \fB/.weechat/python/autoload/\fR then logout, and start WeeChat with

.B weechat\-curses

Top of screen should say what pythons scripts have loaded, and should include shell. Then to run inxi, 
you would enter a command like this: 

.B /shell \-o inxi \-bx

If you leave off the \fB\-o\fR, only you will see the output on your local weechat. WeeChat 
users may also like to check out the weeget.py
.SH INITIALIZATION FILE
.TP 
inxi will read the following configuration/initialization files in the following order: 
.TP
.B /etc/inxi.conf 
.TP
.B $HOME/.inxi/inxi.conf 
.TP
See wiki pages for more information on how to set these up:
.TP 
.I http://code.google.com/p/inxi/wiki/script_configuration_files 
.SH BUGS 
Please report bugs using the following resources. 

You may be asked to run the inxi debugger tool which will upload a data dump of all 
system files for use in debugging inxi. These data dumps are very important since 
they provide us with all the real system data inxi uses to parse out its report. 
.TP
inxi main website/svn/wiki, file an issue report: 
.I https://github.com/smxi/inxi/issues
.TP
post on inxi developer forums: 
.I http://techpatterns.com/forums/forum\-32.html 
.TP
You can also visit 
.I irc.oftc.net \fRchannel:\fI #smxi 
to post issues. 
.SH HOMEPAGE
.I  https://github.com/smxi/inxi
.I  http://smxi.org/
.SH  AUTHOR AND CONTRIBUTORS TO CODE
.B inxi
is is a fork of locsmif's largely unmaintained yet very clever, infobash script. 

Original infobash author and copyright holder:
Copyright (C) 2005\-2007  Michiel de Boer a.k.a. locsmif

inxi version: Copyright (C) 2008\-15 Scott Rogers & Harald Hope

Further fixes (listed as known): Horst Tritremmel <hjt at sidux.com>

Steven Barrett (aka: damentz) \- usb audio patch; swap percent used patch.
Jarett.Stevens \- dmidecode \-M patch for older systems with no /sys 

And a special thanks to the nice people at irc.oftc.net channels #linux\-smokers\-club and #smxi,
who  all really have to be considered to be co\-developers because of their non\-stop enthusiasm 
and willingness to provide real time testing and debugging of inxi development.

Without a wide range of diverse Linux kernel based Free Desktop systems to test on, we could 
never have gotten inxi to be as reliable and solid as it's turning out to be.

And of course, big thanks locsmif, who figured out a lot of the core methods, logic, 
and tricks used in inxi.

Further thanks to the various inxi package maintainers, distro support people, forum
moderators, and others, who contribute ideas, suggestions, and patches.

This Man page was originally created by Gordon Spencer (aka aus9) and is maintained by 
Harald Hope (aka h2 or TechAdmin).
