.TH INXI 8 "2012-06-24" inxi "inxi manual"
.SH NAME
inxi  - Command line system information script for console and IRC 

.SH SYNOPSIS
.B inxi \fR - Single line, short form. Very basic output.

.B inxi \fR[\fB-AbCdDfFGhHiIlMnNopPrRsSu\fR]  \fR[\fB-c  NUMBER\fR] \fR[\fB-v  NUMBER\fR]

.B inxi  \fR[\fB-t \fR(\fBc\fR or\fB m\fR or\fB cm\fR or\fB cm NUMBER\fR)] \fR[\fB-x -OPTION\fR(\fBs\fR)] \fR[\fB-xx -OPTION\fR(\fBs\fR)] \fR[\fB-xxx -OPTION\fR(\fBs\fR)]

.B inxi \fR[\fB--help\fR] \fR[\fB--recommends\fR] \fR[\fB--version\fR] \fR[\fB-@ NUMBER\fR] 

.SH DESCRIPTION
.B inxi\fR is a command line system information script built for for console and IRC. It is also used for forum technical
support, as a debugging tool, to quickly ascertain user system configuration and hardware. inxi shows system 
hardware, CPU, drivers, Xorg, Desktop, Kernel, GCC version(s), Processes, RAM usage, and a wide variety of other 
useful information. 

.B inxi\fR output varies between CLI and IRC, with some default filters and color options applied to IRC use. Script colors can
be turned off if desired with \fB-c 0\fR, or changed using the \fB-c\fR color options listed in the OPTIONS section below.

.SH RUNNING IN IRC CLIENT
To trigger inxi output in your IRC client, pick the appropriate method from the list below:

.TP
.B Xchat, irssi \fR(and many other IRC clients)
.B /exec -o inxi \fR[\fBoptions\fR]

If you leave off the \fB-o\fR, only you will see the output on your local IRC client.
.TP
.B Konversation
.B /cmd inxi \fR[\fBoptions\fR]

To run inxi in konversation as a native script if your distribution or inxi package did not do this for you, 
create this symbolic link: 

.B ln -s /usr/local/bin/inxi /usr/share/kde4/apps/konversation/scripts/inxi

If inxi is somewhere else, change the path /usr/local/bin to wherever it is located.

Then you can start inxi directly, like this:

.B /inxi \fR[\fBoptions\fR]
.TP
.B weechat
.B /shell -o inxi \fR[\fBoptions\fR]

For Weechat to run external scripts like inxi, you have to install shell.py (if you don't already have it). 
To install shell.py, run this command inside of weechat: 

.B /weeget install shell.py

Then to run inxi, you would enter a command like this: 

.B /shell -o inxi -bx

If you leave off the \fB-o\fR, only you will see the output on your local weechat.

.SH PRIVACY AND SECURITY

In order to maintain basic privacy and security, inxi filters out automatically on IRC things like
your network card mac address, WAN and LAN IP, your /home username directory in partitions, 
and a few other things.

Because inxi is often used on forums for support, you can also trigger this filtering with the \fB-z\fR
option (\fB-Fz\fR, for example). To override the IRC filter, you can use the \fB-Z\fR option. This can be useful 
to debug network connection issues online in a private chat, for example.

.SH USING OPTIONS

Options can be combined if they do not conflict. Either group the letters 
together or separate them.

Letters with numbers can have no gap or a gap at your discretion unless using \fB -t\fR.

For example: 
.B inxi -AG\fR or \fBinxi -A -G\fR or \fBinxi -c10

.SH STANDARD OPTIONS 

.TP
.B -A  
Show Audio/sound card information.
.TP
.B -b  
Shows basic output, short form (previously \fB-d\fR). Same as: \fBinxi -v 2
.TP
.B -c \fR[\fB0\fR-\fB32\fR] 
Available color schemes. Scheme number is required. 
  
Supported color schemes: \fB0-32

.TP	 
.B -c \fR[\fB94\fR-\fB99\fR]
Color selectors run a color selector option  prior to inxi starting which lets 
you set the config file value for the selection.

Color selectors for each type display 

(NOTE: irc and global only show safe color set):
.TP
\fB -c 94 \fR   Console, out of X
.TP
\fB -c 95 \fR  	Terminal, running in X - like xTerm
.TP
\fB -c 96 \fR   Gui IRC, running in X - like Xchat, Quassel, 
Konversation etc.
.TP
\fB -c 97 \fR	Console IRC running in X - like irssi in xTerm
.TP
\fB -c 98 \fR	Console IRC not in  X
.TP
\fB -c 99 \fR	Global - Overrides/removes all settings.

Setting specific removes global.

.TP
.B -C  
Show full CPU output, including per CPU clockspeed.
.TP
.B -d  
Shows optical drive data. Same as \fB-Dd\fR. With \fB-x\fR, adds features line to output. 
\fB-xx\fR adds a few more features.
.TP
.B -D  
Show full hard Disk info, not only model, ie: \fI/dev/sda ST380817AS 80.0GB.
.TP
.B -f  
Show all cpu flags used, not just the short list. Not shown with \fB-F\fR to avoid 
spamming.
.TP
.B -F  
Show Full output for inxi. Includes all Upper Case line letters, plus \fB-s\fR and \fB-n\fR.
Does not show extra verbose options like \fB-x -d -f -u -l -o -p -t -r\fR unless you use 
that argument.
.TP
.B -G  
Show Graphic card information (card, x type, resolution, glx renderer, version).
.TP
.B -h
This help menu.
.TP
.B --help
Same as \fB-h\fR
.TP
.B -H
This help menu, plus developer options. Do not use dev options in normal 
operation!
.TP
.B -i  
Show Wan IP address, and shows local interfaces (requires ifconfig network tool). 
Same as -Nni. Not shown with \fB-F\fR for user security reasons, you shouldn't 
paste your local/wan IP.
.TP
.B -I  
Show Information: processes, uptime, memory, irc client, inxi version.
.TP
.B -l  
Show partition labels. Default: short partition \fB-P\fR. For full \fB-p\fR output, use: \fB-pl\fR (or \fB-plu\fR).
.TP
.B -M  
Show machine data. Motherboard, Bios, and if present, System Builder (Like Lenovo).
Older systems/kernels without the required /sys data can use dmidecode instead, run as root.
.TP
.B -n  
Show Advanced Network card information. Same as \fB-Nn\fR. Shows interface, speed, 
mac id, state, etc.
.TP
.B -N  
Show Network card information. With \fB-x\fR, shows PCI BusID, Port number.
.TP
.B -o  
Show unmounted partition information (includes UUID and LABEL if available).
Shows file system type if you have file installed, if you are root OR if you have
added to /etc/sudoers (sudo v. 1.7 or newer): 

.B <username> ALL = NOPASSWD: /usr/bin/file (sample)
.TP
.B -p  
Show full partition information (\fB-P\fR plus all other detected partitions).
.TP
.B -P  
Show Partition information (shows what \fB-v 4\fR would show, but without extra data).
Shows, if detected: / /boot /home /tmp /usr /var. Use \fB-p\fR to see all mounted partitions.
.TP
.B -r  
Show distro repository data. Currently supported repo types:
APT (Debian, Ubuntu + derived versions)

PACMAN (Arch Linux + derived versions)

PISI (Pardus + derived versions)

YUM. (Fedora, Redhat, maybe Suse + derived versions)

(as distro data is collected more will be added. If your's is missing please show us how to get this 
information and we'll try to add it.)
.TP
.B -R
Show RAID data. Shows RAID devices, states, levels, and components, and extra data with \fB-x\fR / \fB-xx\fR. 
If device is resyncing, shows resync progress line as well.
.TP
.B --recommends   
Checks inxi application dependencies + recommends, and directories, then shows
what package(s) you need to install to add support for that feature.
.TP
.B -s
Show sensors output (if sensors installed/configured): mobo/cpu/gpu temp; detected 
fan speeds. Gpu temp only for Fglrx/Nvidia drivers. Nvidia shows screen number for > 1 screens.
.TP
.B -S  
Show System information: host name, kernel, desktop environment (if in X), distro
.TP
.B -t \fR[\fBc\fR or\fB m\fR or\fB cm\fR or\fB cm NUMBER\fR]\fR- Show processes. 
If followed by numbers \fB1-20\fR, shows that number of processes for each type 
(default: \fB5\fR; if in irc, max: \fB5\fR)

Make sure to have no space between letters and numbers (\fB-t cm10\fR - right, \fB-t cm 10\fR - wrong).
.TP
.B -t c \fRcpu only. With \fB-x\fR, shows also memory for that process on same line.
.TP
.B -t m  \fRmemory only. With \fB-x\fR, shows also cpu for that process on same line.
.TP
.B -t cm \fRcpu+memory. With \fB-x\fR, shows also cpu or memory for that process on same line.

.TP
.B -u  
Show partition UUIDs. Default: short partition \fB-P\fR. For full \fB-p\fR output, use: \fB-pu\fR (or \fB-plu\fR).
.TP
.B -U             
Auto-update script. Note: if you installed as root, you must be root to update, 
otherwise user is fine. Also installs /updates this Man Page to: \fB-/usr/share/man/man8\fR
This requires that you be root to write to that directory. 
.TP
.B -V 
inxi version information. Prints information then exits.
.TP
.B --version   
same as \fB-V
.TP
.B -v	
Script verbosity levels. Verbosity level number is required. Should not be used with \fB-b\fR or \fB-F\fR. 

Supported levels: \fB0-7\fR Examples :\fB inxi -v 4 \fR or \fB inxi -v4\fR
.TP
.B -v 0 
- Short output, same as: \fBinxi\fR
.TP
.B -v 1 
- Basic verbose, \fB-S\fR + basic CPU + \fB-G\fR + basic Disk + \fB-I\fR.
.TP
.B -v 2 
- Adds networking card (\fB-N\fR), Machine (\fB-M\fR) data, and shows basic hard disk data 
(names only). Same as: \fBinxi -b
.TP
.B -v 3 
- Adds advanced CPU (\fB-C\fR); network (\fB-n\fR) data; triggers \fB-x\fR advanced data option.
.TP
.B -v 4 
- Adds partition size/filled data (\fB-P\fR) for (if present):/, /home, /var/, /boot
Shows full disk data (\fB-D\fR)
.TP
.B -v 5 
- Adds audio card (\fB-A\fR); sensors (\fB-s\fR), partition label (\fB-l\fR) and UUID (\fB-u\fR), short form of 
optical drives.
.TP
.B -v 6 
- Adds full partition data (\fB-p\fR), unmounted partition data (\fB-o\fR), optical drive data (\fB-d\fR); 
triggers \fB-xx\fR extra data option.
.TP
.B -v 7 
- Adds network IP data (\fB-i\fR); triggers \fB-xxx.
.TP
.B -z  
Adds security filters for IP addresses, Mac, and user home directory name. Default on for irc clients.
.TP
.B -Z  
Absolute override for output filters. Useful for debugging networking issues in irc for example.

.SH EXTRA DATA OPTIONS

These options are for long form only, and can be triggered by one or more \fB-x\fR, like \fB-xx\fR.
Alternately, the \fB-v\fR options trigger them in the following way:
\fB-v 3\fR adds \fB-x\fR; \fB-v 6\fR adds \fB-xx\fR; \fB-v 7\fR adds \fB-xxx\fR

These extra data triggers can be useful for getting more in-depth data on various options.
Can be added to any long form option list, like: \fB-bxx\fR or \fB-Sxxx\fR

There are 3 extra data levels: \fB-x\fR; \fB-xx\fR; and \fB-xxx\fR

The following shows which lines / items get extra information with each extra data level.

.TP 
.B -x -C 
- bogomips on Cpu
.TP
.B -x -d
- Adds items to features line of optical drive; adds rev version to optical drive.
.TP
.B -x -D
- Hdd temp with disk data if you have hddtemp installed, if you are root OR if you have added to
/etc/sudoers (sudo v. 1.7 or newer): 

.B <username> ALL = NOPASSWD: /usr/sbin/hddtemp (sample)
.TP
.B -x -G 
- Direct rendering status for Graphics (in X).
.TP
.B -x -G 
- (for single gpu, nvidia driver) screen number gpu is running on.
.TP
.B -x -i 
- Show IPv6 as well for LAN interface (IF) devices.
.TP
.B -x -I
- Show system GCC, default. With -xx, also show other installed GCC versions.
.TP
.B -x -N -A \fR- Adds version/port(s)/driver version (if available) for Network/Audio;
.TP
.B -x  -N -A -G \fR- Network, audio, graphics, shows PCI Bus ID/Usb ID number of card
.TP
.B -x -R 
- Shows component raid id. Adds second RAID Info line: raid level; report on drives 
(like 5/5); blocks; chunk size; bitmap (if present). Resync line, shows blocks synced/total blocks.
.TP
.B -x -S 
- Desktop toolkit if avaliable (GNOME/XFCE/KDE only); Kernel gcc version
.TP
.B -x -t 
- Adds memory use output to cpu (\fB-xt c\fR), and cpu use to memory (\fB-xt m\fR).
.TP
.B -xx -D 
- Adds disk serial number
.TP
.B -xx -I 
- Adds other detected installed gcc versions to primary gcc output (if present).
.TP
.B -xx -M 
- Adds chassis information, if any data for that is available.
.TP
.B -xx -R
- Adds superblock (if present); algorythm, U data. Adds system info line (kernel support,  
read ahead, raid events). Adds if present, unused device line.  If device is resyncing, shows 
resync progress line as well
.TP
.B -xx -S 
- Adds, if run in X, display manager type to Desktop information, if present. If none, shows N/A.
Supports most known display managers, like xdm, gdm, kdm, slim, lightdm, or mdm.
.TP
.B -xx -@ <11-14>
- Automatically uploads debugger data tar.gz file to \fIftp.techpatterns.com\fR.
.TP
.B -xxx -S 
- Adds, if run in X, shell/panel type info to Desktop information, if present. If none, shows nothing.
Supports some current desktop extras like gnome-panel, lxde-panel, and others. Added mainly for Mint support.

.SH DEBUGGING OPTIONS
.TP
.B -%  
Overrides defective or corrupted data.
.TP
.B -@  
Triggers debugger output. Requires debugging level \fB1-14\fR (\fB8-10\fR - logging of data).
Less than 8 just triggers inxi debugger output on screen.
.TP
.B -@  \fR[\fB1\fR-\fB7\fR] 
- On screen debugger output
.TP
.B -@ 8    
- Basic logging. Check \fI /home/yourname/.inxi/inxi*.log 
.TP
.B -@ 9    
- Full file/sys info logging
.TP
.B -@ 10  
- Color logging.
.TP
.B -@ <11-14>
The following create a tar.gz file of system data, plus collecting the inxi output to file:
To automatically upload debugger data tar.gz file to \fIftp.techpatterns.com\fR: \fBinxi -xx@ <11-14>\fR
For alternate ftp upload locations: Example: 

\fBinxi -! \fIftp.yourserver.com/incoming\fB -xx@ 14\fR

.TP
.B -@ 11 
- With data file of xiin read of /sys
.TP
.B -@ 12 
- With xorg conf and log data, xrandr, xprop, xdpyinfo, glxinfo etc.
.TP
.B -@ 13 
- With data from dev, disks, partitions, etc., plus xiin data file.
.TP
.B -@ 14 
- Everything, full data collection

.SH SUPPORTED IRC CLIENTS  

BitchX, Gaim/Pidgin, ircII, Irssi, Konversation, Kopete, KSirc, KVIrc, Weechat, and Xchat. Plus any others that
are capable of displaying either built in or external script output.

.SH INITIALIZATION FILE
.TP 
inxi will read the following configuration/initialization files in the following order: 
.TP
.B /etc/inxi.conf 
.TP
.B $HOME/.inxi/inxi.conf 
.TP
See wiki pages for more information on how to set these up:
.TP 
.I http://code.google.com/p/inxi/wiki/script_configuration_files 

.SH BUGS 
Please report bugs using the following resources. 

You may be asked to run the inxi debugger tool which will upload a data dump of all 
system files for use in debugging inxi. These data dumps are very important since 
they provide us with all the real system data inxi uses to parse out its report. 

.TP
inxi wiki, file an issue report: 
.I http://code.google.com/p/inxi/issues/list 
.TP
post on inxi developer forums: 
.I http://techpatterns.com/forums/forum-32.html 
.TP
You can also visit 
.I irc.oftc.net channel: #smxi 
to post issues. 

.SH HOMEPAGE
.I  http://code.google.com/p/inxi

.SH  AUTHOR AND CONTRIBUTORS TO CODE

.B inxi
.R is is a fork of locsmif's largely unmaintained yet very clever, infobash script. 

Original infobash author and copyright holder:
Copyright (C) 2005-2007  Michiel de Boer a.k.a. locsmif

inxi version: Copyright (C) 2008-12 Scott Rogers & Harald Hope

Further fixes (listed as known): Horst Tritremmel <hjt at sidux.com>

Steven Barrett (aka: damentz) - usb audio patch; swap percent used patch

And a special thanks to the nice people at irc.oftc.net channels #linux-smokers-club and #smxi,
who  all really have to be considered to be co-developers because of their non-stop enthusiasm 
and willingness to provide real time testing and debugging of inxi development.

Without a wide range of diverse Linux kernel based Free Desktop systems to test on, we could 
never have gotten inxi to be as reliable and solid as it's turning out to be.

And of course, big thanks locsmif, who figured out a lot of the core methods, logic, 
and tricks used in inxi.

Further thanks to the various inxi package maintainers, distro support people, forum
moderators, and others, who contribute ideas, suggestions, and patches.

This Man page was created by aus9, with help from Harald (aka h2).
