.TH INXI 1 "2018\-09\-10" inxi "inxi manual"
.SH NAME
inxi  \- Command line system information script for console and IRC
.SH SYNOPSIS
\fBinxi\fR

\fBinxi\fR [\fB\-AbBCdDfFGhiIlmMnNopPrRsSuUVwzZ\fR]

\fBinxi\fR [\fB\-c NUMBER\fR] [\fB\-t\fR [\fBc\fR|\fBm\fR|\fBcm\fR|\fBmc\fR]
[\fBNUMBER\fR]] [\fB\-v NUMBER\fR] [\fB\-W LOCATION\fR] 
[\fB\-\-weather\-unit\fR {\fBm\fR|\fBi\fR|\fBmi\fR|\fBim\fR}] [\fB\-y WIDTH\fR] 

\fBinxi\fR [\fB\-\-recommends\fR] \fR[\fB\-\-slots\fR] \fR[\fB\-\-usb\fR]

\fBinxi\fB [\fB\-x\fR|\fB\-xx\fR|\fB\-xxx\fR|\fB\-a\fR|\fB\-\-admin\fR] \fB\-OPTION(s)\fR

All options have long form variants \- see below for these and more advanced options.

.SH DESCRIPTION
\fBinxi\fR is a command line system information script built for console
and IRC. It is also used a debugging tool for forum technical support
to quickly ascertain users' system configurations and hardware. inxi shows
system hardware, CPU, drivers, Xorg, Desktop, Kernel, gcc version(s), Processes,
RAM usage, and a wide variety of other useful information.

\fBinxi\fR output varies depending on whether it is being used on CLI or IRC,
with some default filters and color options applied only for IRC use.
Script colors can be turned off if desired with \fB\-c 0\fR, or changed 
using the \fB\-c\fR color options listed in the STANDARD OPTIONS section below.

.SH PRIVACY AND SECURITY
In order to maintain basic privacy and security, inxi used on IRC automatically
filters out your network device MAC address, WAN and LAN IP, your \fB/home\fR
username directory in partitions, and a few other items.

Because inxi is often used on forums for support, you can also trigger this
filtering with the \fB\-z\fR option (\fB\-Fz\fR, for example). To override
the IRC filter, you can use the \fB\-Z\fR option. This can be useful in debugging
network connection issues online in a private chat, for example.

.SH USING OPTIONS
Options can be combined if they do not conflict. You can either group the letters
together or separate them.

Letters with numbers can have no gap or a gap at your discretion, except when
using \fB \-t\fR.

For example:
.B inxi
\fB\-AG\fR or \fBinxi \-A \-G\fR or \fBinxi \-c10\fR

Note that all the short form options have long form equivalents, which are
listed below. However, usually the short form is used in examples in order to
keep things simple.

.SH STANDARD OPTIONS
.TP
.B \-A\fR,\fB \-\-audio\fR
Show Audio/sound card(s) information, including card driver.
.TP
.B \-b\fR,\fB \-\-basic\fR
Show basic output, short form. Same as: \fBinxi \-v 2\fR
.TP
.B \-B\fR,\fB \-\-battery\fR
Show system battery (\fBID\-x\fR) data, charge, condition, plus extra information 
(if battery present). Uses \fB/sys\fR or, for BSDs without systctl battery data, 
\fBdmidecode\fR. \fBdmidecode\fR does not have very much information, and none 
about current battery state/charge/voltage. Supports multiple batteries when 
using \fB/sys\fR data.

Note that for \fBcharge\fR, the output shows the current charge, as well as its
value as a percentage of the available capacity, which can be less than the original design
capacity. In the following example, the actual current available capacity of the battery
is \fB22.2 Wh\fR.

\fBcharge: 20.1 Wh 95.4%\fR

The \fBcondition\fR item shows the remaining available capacity / original design
capacity, and then this figure as a percentage of original capacity available in the battery.

\fBcondition: 22.2/36.4 Wh (61%)\fR

With \fB\-x\fR shows attached \fBDevice\-x\fR information (mouse, keyboard, etc.) 
if they are battery powered.

.TP
.B \-c\fR,\fB \-\-color\fR \fR[\fB0\fR\-\fB42\fR]
Set color scheme. If no scheme number is supplied, 0 is assumed.

.TP
.B \-c \fR[\fB94\fR\-\fB99\fR]

These color selectors run a color selector option  prior to inxi starting which lets
you set the config file value for the selection.

NOTE: All configuration file set color values are removed when output is 
piped or redirected. You must use the explicit runtime \fB\-c <color number>\fR option
if you want color codes to be present in the piped/redirected output.

Color selectors for each type display (NOTE: IRC and global only show safe color set):
.TP
.B \-c 94\fR
\- Console, out of X.
.TP
.B \-c 95\fR
\- Terminal, running in X \- like xTerm.
.TP
.B \-c 96\fR
\- GUI IRC, running in X \- like XChat, Quassel,
Konversation etc.
.TP
.B \-c 97\fR
\- Console IRC running in X \- like irssi in xTerm.
.TP
.B \-c 98\fR
\- Console IRC not in  X.
.TP
.B \-c 99\fR
\- Global \- Overrides/removes all settings.

Setting a specific color type removes the global color selection.
.TP
.B \-C\fR,\fB \-\-cpu\fR
Show full CPU output, including per CPU clock speed and CPU max speed (if available).
If max speed data present, shows \fB(max)\fR in short output formats (\fBinxi\fR,
\fBinxi \-b\fR) if actual CPU speed matches max CPU speed. If max CPU speed does
not match actual CPU speed, shows both actual and max speed information.
See \fB\-x\fR for more options.

For certain CPUs (some ARM, and AMD Zen family) shows CPU die count.

The details for each CPU include a technical description e.g. \fBtype: MT MCP\fR

* \fBMT\fR \- Multi/Hyper Threaded CPU, more than 1 thread per core (previously \fBHT\fR).

* \fBMCM\fR \- Multi Chip Model (more than 1 die per CPU).

* \fBMCP\fR \- Multi Core Processor (more than 1 core per CPU).

* \fBSMP\fR \- Symmetric Multi Processing (more than 1 physical CPU).

* \fBUP\fR \- Uni (single core) Processor.

.TP
.B \-d\fR,\fB \-\-disk\-full\fR,\fB\-\-optical\fR
Show optical drive data as well as \fB\-D\fR hard drive data. With \fB\-x\fR, adds a
feature line to the output. Also shows floppy disks if present. Note that there is
no current way to get any information about the floppy device that I am aware of,
so it will simply show the floppy ID without any extra data. \fB\-xx\fR adds a
few more features.
.TP
.B \-D\fR,\fB \-\-disk\fR
Show Hard Disk info. Shows total disk space and used percentage. The disk used 
percentage includes space used by swap partition(s), since those are not usable 
for data storage. Note that with RAID disks, the percentage will be wrong since 
the total is computed from the disk sizes, but used is computed from mounted 
partition used percentages. This small defect may get corrected in the future. 
Also, unmounted partitions are not counted in disk use percentages since inxi 
has no access to the used amount.

Also shows per disk information: Disk ID, type (if present), vendor (if detected), 
model, and size. See \fBExtra Data Options\fR for more features.
.TP
.B \-f\fR,\fB \-\-flags\fR
Show all CPU flags used, not just the short list. Not shown with \fB\-F\fR in order
to avoid spamming. ARM CPUs: show \fBfeatures\fR items.
.TP
.B \-F\fR,\fB \-\-full\fR
Show Full output for inxi. Includes all Upper Case line letters except \fB\-W\fR,
plus \fB\-s\fR and \fB\-n\fR. Does not show extra verbose options such as
\fB\-d \-f \-i \-l \-m \-o \-p \-r \-t \-u \-x\fR unless you use those arguments in
the command, e.g.: \fBinxi \-Frmxx\fR
.TP
.B \-G\fR,\fB \-\-graphics\fR
Show Graphic card(s) information, including details of card and card driver,
display protocol (if available), display server (vendor and version number), e.g.:

\fBDisplay: x11 server: Xorg 1.15.1\fR

If protocol is not detected, shows:

\fBDisplay: server: Xorg 1.15.1\fR

Also shows screen resolution(s), OpenGL renderer, OpenGL core profile version/OpenGL
version.

Compositor information will show if detected using \fB\-xx\fR option.
.TP
.B \-h\fR,\fB \-\-help\fR
The help menu. Features dynamic sizing to fit into terminal window. Set script
global \fBCOLS_MAX_CONSOLE\fR if you want a different default value, or
use \fB\-y <width>\fR to temporarily override the defaults or actual window width.
.TP
.B \-i\fR,\fB \-\-ip\fR
Show WAN IP address and local interfaces (latter requires \fBifconfig\fR or
\fBip\fR network tool), as well as network output from \fB\-n\fR.
Not shown with \fB\-F\fR for user security reasons. You shouldn't paste your
local/WAN IP. Shows both IPv4 and IPv6 link IP addresses.

.TP
.B \-I\fR,\fB \-\-info\fR
Show Information: processes, uptime, memory, IRC client (or shell type if run in
shell, not IRC), inxi version. See \fB\-x\fR and \fB\-xx\fR for extra information
(init type/version, runlevel). 

Rasberry Pi only: uses \fBvcgencmd get_mem gpu\fR to get gpu RAM amount, 
if user is in video group and \fBvcgencmd\fR is installed. Uses 
this result to increase the \fBMemory:\fR amount and \fBused:\fR amounts.
.TP
.B \-l\fR,\fB \-\-label\fR
Show partition labels. Default: main partitions \fB\-P\fR. For full \fB\-p\fR output,
use: \fB\-pl\fR.
.TP
.B \-m\fR,\fB \-\-memory\fR
Memory (RAM) data. Does not display with  \fB\-b\fR or  \fB\-F\fR unless you use \fB\-m\fR
explicitly. Ordered by system board physical system memory array(s) (\fBArray\-[number]\fR),
and individual memory devices (\fBDevice\-[number]\fR). Physical memory
array  data shows array capacity, number of devices supported, and Error Correction
information. Devices shows locator data (highly variable in syntax), size, speed,
type (eg: \fBtype: DDR3\fR).

Note that \fB\-m\fR uses \fBdmidecode\fR, which must be run as root (or start
\fBinxi\fR with \fBsudo\fR), unless you figure out how to set up sudo to permit
dmidecode to read \fB/dev/mem\fR as user. Note that speed will not show if \fBNo Module
Installed\fR is found in \fBsize\fR. This will also turn off Bus Width data output if it is null.

If memory information was found, and if the \fB\-I\fR line or the \fB\-tm\fR item have
not been triggered, will also print the RAM used/total.

Because \fBdmidecode\fR data is extremely unreliable, inxi will try to make best guesses.
If you see \fB(check)\fR after the capacity number, you should check it with the
specifications. \fB(est)\fR is slightly more reliable, but you should still check
the real specifications before buying RAM. Unfortunately there is nothing \fBinxi\fR
can do to get truly reliable data about the system RAM; maybe one day the kernel devs
will put this data into \fB/sys\fR, and make it real data, taken from the actual system,
not dmi data. For most people, the data will be right, but a significant percentage of
users will have either a wrong max module size, if present, or max capacity.
.TP
.B \-M\fR,\fB \-\-machine\fR
Show machine data. Device, Motherboard, BIOS, and if present, System Builder (Like Lenovo).
Older systems/kernels without the required \fB/sys\fR data can use \fBdmidecode\fR instead, run
as root. If using \fBdmidecode\fR, may also show BIOS/UEFI revision as well as version.
\fB\-\-dmidecode\fR forces use of \fBdmidecode\fR data instead of \fB/sys\fR.
Will also attempt to show if the system was booted by BIOS, UEFI, or UEFI [Legacy], the
latter being legacy BIOS boot mode in a system board using UEFI.

Device information requires either \fB/sys\fR or \fBdmidecode\fR. Note that 'other\-vm?'
is a type that means it's usually a VM, but inxi failed to detect which type, or
positively confirm which VM it is. Primary VM identification is via systemd\-detect\-virt
but fallback tests that should also support some BSDs are used. Less commonly
used or harder to detect VMs may not be correctly detected. If you get an incorrect output,
post an issue and we'll get it fixed if possible.

Due to unreliable vendor data, device type will show: desktop, laptop, notebook, server,
blade, plus some obscure stuff that inxi is unlikely to ever run on.
.TP
.B \-n\fR,\fB \-\-network\-advanced\fR
Show Advanced Network card information in addition to that produced by \fB\-N\fR.
Shows interface, speed, MAC ID, state, etc.
.TP
.B \-N\fR,\fB \-\-network\fR
Show Network card(s) information, including card driver. With \fB\-x\fR, shows PCI BusID, 
Port number.
.TP
.B \-o\fR,\fB \-\-unmounted\fR
Show unmounted partition information (includes UUID and LABEL if available).
Shows file system type if you have \fBlsblk\fR installed (Linux only). For BSD/GNU Linux:
shows file system type if \fBfile\fR is installed, and if you are root or
if you have added to \fB/etc/sudoers\fR (sudo v. 1.7 or newer):

.B <username> ALL = NOPASSWD: /usr/bin/file (sample)

Does not show components (partitions that create the md\-raid array) of md\-raid arrays.
.TP
.B \-p\fR,\fB \-\-partitions\-full\fR
Show full Partition information (\fB\-P\fR plus all other detected mounted partitions).
.TP
.B \-P\fR,\fB \-\-partitions\fR
Show basic Partition information.
Shows, if detected: \fB/ /boot /home /opt /tmp /usr /usr/home /var /var/tmp /var/log\fR.
Use \fB\-p\fR to see all mounted partitions.
.TP
.B \-r\fR,\fB \-\-repos\fR
Show distro repository data. Currently supported repo types:

\fBAPK\fR (Alpine Linux + derived versions)

\fBAPT\fR (Debian, Ubuntu + derived versions, as well as RPM based 
APT distros like PCLinuxOS or Alt-Linux)

\fBEOPKG\fR (Solus)

\fBPACMAN\fR (Arch Linux, KaOS + derived versions)

\fBPACMAN\-G2\fR (Frugalware + derived versions)

\fBPISI\fR (Pardus + derived versions)

\fBPORTAGE\fR (Gentoo, Sabayon + derived versions)

\fBPORTS\fR (OpenBSD, FreeBSD, NetBSD + derived OS types)

\fBSLACKPKG\fR (Slackware + derived versions)

\fBTCE\fR (TinyCore)

\fBURPMQ\fR (Mandriva, Mageia + derived versions)

\fBYUM/ZYPP\fR (Fedora, Red Hat, Suse + derived versions)

More will be added as distro data is collected. If yours is missing please
show us how to get this information and we'll try to add it.
.TP
.B \-R\fR,\fB \-\-raid\fR
Show RAID data. Shows RAID devices, states, levels and components, and
extra data with \fB\-x\fR / \fB\-xx\fR.

md\-raid: If device is resyncing, also shows resync progress line.

Note: Only md\-raid and ZFS are currently supported. Other software RAID types could
be added, but only if users supply all data required, and if the software
RAID actually can be made to give the required output.

If hardware RAID is detected, shows basic information. Due to complexity
of adding hardware RAID device disk / RAID reports, those will only be added 
if there is demand, and reasonable reporting tools. 

.TP
.B \-\-recommends\fR
Checks inxi application dependencies and recommends, as well as directories,
then shows what package(s) you need to install to add support for each feature.
.TP
.B \-s\fR,\fB \-\-sensors\fR
Show output from sensors if sensors installed/configured: Motherboard/CPU/GPU
temperatures; detected fan speeds. GPU temperature when available. Nvidia shows
screen number for multiple screens. IPMI sensors are also used (root required)
if present.
.
.TP
.B \-\-slots\fR
Show PCI slots with type, speed, and status information.
.TP
.B \-S\fR,\fB \-\-system\fR
Show System information: host name, kernel, desktop environment (if in X),
distro. With \fB\-xx\fR show dm \- or startx \- (only shows if present and
running if out of X), and if in X, with \fB\-xxx\fR show more desktop info,
e.g. taskbar or panel.
.TP
.B \-t\fR,\fB \-\-processes\fR
[\fBc\fR|\fBm\fR|\fBcm\fR|\fBmc NUMBER\fR] Show processes. If no arguments, defaults to \fBcm\fR.
If followed by a number, shows that number of processes for each type
(default: \fB5\fR; if in IRC, max: \fB5\fR)

Make sure that there is no space between letters and numbers (e.g. write as \fB\-t cm10\fR).
.TP
.B \-t c\fR
\- CPU only. With \fB\-x\fR, also shows memory for that process on same line.
.TP
.B \-t m\fR
\- memory only. With \fB\-x\fR, also shows CPU for that process on same line.
If the \-I line is not triggered, will also show the system RAM used/total
information.
.TP
.B \-t cm\fR
\- CPU+memory. With \fB\-x\fR, shows also CPU or memory for that process on
same line.

.TP
.B \-\-usb\fR
Show USB data for attached Hubs and Devices. Hubs also show number of ports. 
Be aware that a port is not always external, some may be internal, and either
used or unused (for example, a motherboard USB header connector that is not used).

Hubs and Devices are listed in order of BusID.

BusID is generally in this format: BusID-port[.port][.port]:DeviceID

Device ID is a number created by the kernel, and has no necessary ordering
or sequence connection, but can be used to match this output to lsusb
values, which generally shows BusID / DeviceID (except for tree view, which
shows ports).

Examples: \fRDevice-3: 4-3.2.1:2\fR or \fRHub: 4-0:1\fR

.TP
.B \-u\fR,\fB \-\-uuid\fR
Show partition UUIDs. Default: main partitions \fB\-P\fR. For full \fB\-p\fR
output, use: \fB\-pu\fR.
.TP
.B \-U\fR,\fB \-\-update\fR
Note \- Maintainer may have disabled this function.

If inxi \fB\-h\fR has no listing for \fB\-U\fR then it's disabled.

Auto\-update script. Note: if you installed as root, you must be root to
update, otherwise user is fine. Also installs / updates this man page to:
\fB/usr/local/share/man/man1\fR (if \fB/usr/local/share/man/\fR exists
AND there is no inxi man page in \fB/usr/share/man/man1\fR, otherwise it
goes to \fB/usr/share/man/man1\fR). This requires that you be root to write
to that directory. See \fB\-\-man\fR or \fB\-\-no\-man\fR to force or disable 
man install.

.TP
.B \-V\fR,\fB \-\-version\fR
inxi version information. Prints information then exits.
.TP
.B \-v\fR,\fB \-\-verbosity\fR
Script verbosity levels. If no verbosity level number is given, 0 is assumed.
Should not be used with \fB\-b\fR or \fB\-F\fR.

Supported levels: \fB0\-8\fR Examples :\fB inxi \-v 4 \fR or \fB inxi \-v4\fR
.TP
.B \-v 0
\- Short output, same as: \fBinxi\fR
.TP
.B \-v 1
\- Basic verbose, \fB\-S\fR + basic CPU (cores, type, clock speed, and min/max
speeds, if available) + \fB\-G\fR + basic Disk + \fB\-I\fR.
.TP
.B \-v 2
\- Adds networking card (\fB\-N\fR), Machine (\fB\-M\fR) data, Battery (\fB\-B\fR)
(if available). Same as: \fBinxi \-b\fR
.TP
.B \-v 3
\- Adds advanced CPU (\fB\-C\fR) and network (\fB\-n\fR) data; triggers \fB\-x\fR
advanced data option.
.TP
.B \-v 4
\- Adds partition size/used data (\fB\-P\fR) for (if present):
\fB/ /home /var/ /boot\fR. Shows full disk data (\fB\-D\fR)
.TP
.B \-v 5
\- Adds audio card (\fB\-A\fR), memory/RAM (\fB\-m\fR), sensors (\fB\-s\fR),
partition label (\fB\-l\fR), UUID (\fB\-u\fR), and short form of
optical drives.
.TP
.B \-v 6
\- Adds full mounted partition data (\fB\-p\fR), unmounted partition data (\fB\-o\fR),
optical drive data (\fB\-d\fR), USB (\fB\-\-usb\fR); triggers \fB\-xx\fR extra data option.
.TP
.B \-v 7
\- Adds network IP data (\fB\-i\fR); triggers \fB\-xxx\fR
.TP
.B \-v 8
\- All system data available. Adds Repos (\fB\-r\fR), PCI slots (\fB\-\-slots\fR), processes
(\fB\-tcm\fR), admin (\fB\-\-admin\fR). Useful for testing output and to see what data 
you can get from your system.
.TP
.B \-w\fR,\fB \-\-weather\fR
Adds weather line. Note, this depends on an unreliable API so it may not always
be working in the future. To get weather for an alternate location, use
\fB\-W\fR. See also \fB\-x\fR, \fB\-xx\fR, \fB\-xxx\fR options.
Please note that your distribution's maintainer may chose to disable this feature.
.TP
.B \-W\fR,\fB \-\-weather\-location <location_string>\fR
Get weather/time for an alternate location. Accepts postal/zip code,
city,state pair, or latitude,longitude. Note: city/country/state names must not
contain spaces. Replace spaces with '\fB+\fR' sign. Don't place spaces around any commas.
Use only ASCII letters in city/state/country names, sorry.

Examples: \fB\-W 95623\fR OR \fB\-W Boston,MA\fR OR \fB\-W45.5234,\-122.6762\fR
OR \fB\-W new+york,ny\fR OR \fB\-W bodo,norway\fR.
.TP
.B \-\-weather\-unit <unit>\fR
[\fBm\fR|\fBi\fR|\fBmi\fR|\fBim\fR] Sets weather units to metric (\fBm\fR), imperial (\fBi\fR), 
metric (imperial) (\fBmi\fR, default), imperial (metric) (\fBim\fR). If metric or imperial 
not found,sets to default value, or \fBN/A\fR.
.TP
.B \-y\fR,\fB \-\-width <integer>\fR
This is an absolute width override which sets the output line width max.
Overrides \fBCOLS_MAX_IRC\fR / \fBCOLS_MAX_CONSOLE\fR globals, or the
actual widths of the terminal. \fB80\fR is the minimum width supported. 
\fB\-1\fR removes width limits. Example: \fBinxi \-Fxx\ \-y 130\fR
.TP
.B \-z\fR,\fB \-\-filter\fR
Adds security filters for IP addresses, serial numbers, MAC, 
location (\fB\-w\fR), and user home directory name. On by default for IRC clients.
.TP
.B \-Z\fR,\fB \-\-filter\-override\fR
Absolute override for output filters. Useful for debugging networking
issues in IRC for example.
.SH EXTRA DATA OPTIONS
These options can be triggered by one or more \fB\-x\fR.
Alternatively, the \fB\-v\fR options trigger them in the following
way: \fB\-v 3\fR adds \fB\-x\fR;
\fB\-v 6\fR adds \fB\-xx\fR; \fB\-v 7\fR adds \fB\-xxx\fR

These extra data triggers can be useful for getting more in\-depth
data on various options. They can be added to any long form option list,
e.g.: \fB\-bxx\fR or \fB\-Sxxx\fR

There are 3 extra data levels:

\fB\-x\fR, \fB\-xx\fR, \fB\-xxx\fR

OR

\fB\-\-extra 1\fR, \fB\-\-extra 2\fR, \fB\-\-extra 3\fR

The following details show which lines / items display extra information for each
extra data level.
.TP
.B \-x \-A\fR
\- Adds version/port(s)/driver version (if available) for each Audio
device.

\- Adds PCI Bus ID/USB ID number of each Audio device.
.TP
.B \-x \-B\fR
\- Adds vendor/model, battery status (if battery present).

\- Adds attached battery powered peripherals (\fBDevice\-[number]:\fR) if 
detected (keyboard, mouse, etc.).
.TP
.B \-x \-C\fR
\- Adds bogomips on CPU (if available)

\- Adds CPU Flags (short list).

\- Adds CPU microarchitecture + revision (e.g. Sandy Bridge, K8, ARMv8, P6,
etc.). Only shows data if detected. Newer microarchitectures will have
to be added as they appear, and require the CPU family ID and model ID.

Examples: \fBarch: Sandy Bridge rev: 2\fR, \fBarch: K8 rev.F+ rev: 2\fR
.TP
.B \-x \-d\fR
\- Adds more items to \fBFeatures\fR line of optical drive; 
dds rev version to optical drive.
.TP
.B \-x \-D\fR
\- Adds HDD temperature with disk data if you have hddtemp installed, if you are root
or if you have added to \fB/etc/sudoers\fR (sudo v. 1.7 or newer):

.B <username> ALL = NOPASSWD: /usr/sbin/hddtemp (sample)
.TP
.B \-x \-G\fR
\- Adds direct rendering status.

\- Adds (for single GPU, nvidia driver) screen number that GPU is running on.

\- Adds PCI Bus ID/USB ID number of each Graphics card.
.TP
.B \-x \-i\fR
\- Adds IP v6 additional scope data, like Global, Site, Temporary for
each interface.

Note that there is no way I am aware of to filter out the deprecated
IP v6 scope site/global temporary addresses from the output of
\fBifconfig\fR. The \fBip\fR tool shows that clearly.

\fBip\-v6\-temporary\fR \- (\fBip\fR tool only), scope global temporary.
Scope global temporary deprecated is not shown

\fBip\-v6\-global\fR \- scope global (\fBifconfig\fR will show this for
all types, global, global temporary, and global temporary deprecated,
\fBip\fR shows it only for global)

\fBip\-v6\-link\fR \- scope link (\fBip\fR/\fBifconfig\fR) \- default
for \fB\-i\fR.

\fBip\-v6\-site\fR \- scope site (\fBip\fR/\fBifconfig\fR). This has been
deprecated in IPv6, but still exists. \fBifconfig\fR may show multiple site
values, as with global temporary, and global temporary deprecated.

\fBip\-v6\-unknown\fR \- unknown scope

.TP
.B \-x \-I\fR
\- Adds current init system (and init rc in some cases, like OpenRC).
With \fB\-xx\fR, shows init/rc version number, if available.

\- Adds default system gcc. With \fB\-xx\fR, also show other installed gcc
versions.

\- Adds current runlevel (not available with all init systems).

\- If in shell (i.e. not in IRC client), adds shell version number, if available.
.TP
.B \-x \-m\fR
\- If present, adds maximum memory module/device size in the Array line.
Only some systems will have this data available. Shows estimate if it can
generate one.

\- Adds device type in the Device line.
.TP
.B \-x \-N\fR
\- Adds version/port(s)/driver version (if available) for each Network card;

\- Adds PCI Bus ID/USB ID number of each Network card.
.TP
.B \-x \-R\fR
\- md\-raid: Adds second RAID Info line with extra data: blocks, chunk size,
bitmap (if present). Resync line, shows blocks synced/total blocks.

\- Hardware RAID: Adds driver version, bus ID.
.TP
.B \-x \-s\fR
\- Adds basic voltages: 12v, 5v, 3.3v, vbat (\fBipmi\fR, \fBlm-sensors\fR if present).
.TP
.B \-x \-S\fR
\- Adds Kernel gcc version.

\- Adds to \fBDistro:\fR \fBbase:\fR if detected. System base will only be seen on
a subset of distributions. The distro must be both derived from a parent distro (e.g. Mint from 
Ubuntu), and explicitly added to the supported distributions for this feature. Due to 
the complexity of distribution identification, these will only be added as relatively solid
methods are found for each distribution system base detection.
.TP
.B \-x \-t\fR
\- Adds memory use output to CPU (\fB\-xt c\fR), and CPU use to memory
(\fB\-xt m\fR).
.TP
.B \-x \-\-usb\fR
\- For Devices, adds driver(s).
.TP
.B \-x \-w\fR,\fB \-W\fR
\- Adds humidity and barometric pressure.

\- Adds wind speed and direction.
.TP
.B \-xx \-A\fR
\- Adds vendor:product ID for each Audio device.
.TP
.B \-xx \-B\fR
\- Adds serial number, voltage (if available). Note that \fBvolts\fR shows the 
data (if available) as the voltage now / minimum design voltage.
.TP
.B \-xx \-C\fR
\- Adds \fBL1 cache:\fR and \fBL3 cache:\fR if either are available. Requires 
dmidecode and sudo/root.
.TP
.B \-xx \-D\fR
\- Adds disk serial number.

\- Adds disk speed (if available). This is the theoretical top speed of the 
device as reported. This speed may be restricted by system board limits, eg. 
a SATA 3 drive on a SATA 2 board may report SATA 2 speeds, but this is not 
completely consistent, sometimes a SATA 3 device on a SATA 2 board reports
its design speed.

NVMe drives: adds lanes, and (per direction) speed is calculated with 
lane speed * lanes * PCIe overhead. PCIe 1 and 2 have data rates of 
GT/s * .8  = Gb/s (10 bits required to transfer 8 bits of data). 
PCIe 3 and greater transfer data at a rate of GT/s * 128/130 * lanes = Gb/s 
(130 bits required to transfer 128 bits of data).

For a PCIe 3 NVMe drive, with speed of \fB8 GT/s\fR and \fB4\fR lanes 
(\fB8GT/s * 128/130 * 4 = 31.6 Gb/s\fR): 

\fBspeed: 31.6 Gb/s lanes: 4\fR
.TP
.B \-xx \-G\fR
\- Adds vendor:product ID of each Graphics card.

\- Adds compositor, if found (experimental).

\- For free drivers, adds OpenGL compatibility version number if  available.
For nonfree drivers, the core version and compatibility versions are usually
the same. Example:

\fBv: 3.3 Mesa 11.2.0 compat\-v: 3.0\fR

\- If available, shows \fBalternate:\fR Xorg drivers. This means a driver on 
the default list of drivers Xorg automatically checks for the card, but which 
is not installed. For example, if you have \fBnouveau\fR driver, \fBnvidia\fR would 
show as alternate if it was not installed. Note that \fBalternate:\fR does NOT mean you 
should have it, it's just one of the drivers Xorg checks to see if is present 
and loaded when checking the card. This can let you know there are other driver options.
Note that if you have explicitly set the driver in \fBxorg.conf\fR, Xorg will not 
create this automatic check driver list.

.TP
.B \-xx \-I\fR
\- Adds init type version number (and rc if present).

\- Adds other detected installed gcc versions (if present).

\- Adds system default runlevel, if detected. Supports Systemd/Upstart/SysVinit
type defaults.

\- Adds parent program (or tty) that started shell, if not IRC client.
.TP
.B \-xx \-m\fR
\- Adds memory device Manufacturer.

\- Adds  memory device Part Number (\fBpart\-no:\fR). Useful for ordering new or
replacement memory sticks etc. Part numbers are unique, particularly
if you use the word \fBmemory\fR in the search as well. With \fB\-xxx\fR,
also shows serial number.

\- Adds single/double bank memory, if data is found. Note, this may not be 100% right
all of the time since it depends on the order that data is found in \fBdmidecode\fR
output for \fBtype 6\fR and \fBtype 17\fR.
.TP
.B \-xx \-M\fR
\- Adds chassis information, if data is available. Also shows BIOS
ROM size if using \fBdmidecode\fR.
.TP
.B \-xx \-N\fR
\- Adds vendor:product ID for each Network card.
.TP
.B \-xx \-R\fR
\- md\-raid: Adds superblock (if present) and algorithm. If resync,
shows progress bar.

\- Hardware RAID: Adds Chip vendor:product ID.
.TP
.B \-xx \-s\fR
\- Adds DIMM/SOC voltages, if present (\fBipmi\fR only).
.TP
.B \-xx \-S\fR
\- Adds display manager (\fBdm\fR) type, if present. If none, shows N/A. 
Supports most known display managers, including gdm, gdm3,
idm, kdm, lightdm, lxdm, mdm, nodm, sddm, slim, tint, wdm, and xdm.

\- Adds, if run in X, window manager type (\fBwm\fR), if available.
Not all window managers are supported. Some desktops support using more than one
window manager, so this can be useful to see what window manager is actually running.
If none found, shows nothing. Uses a less accurate fallback tool \fBwmctrl\fR 
if \fBps\fR tests fail to find data.

\- Adds desktop toolkit (\fBtk\fR), if available (Xfce/KDE/Trinity).
.TP
.B \-xx \-\-slots\fR
\- Adds slot length.
.TP
.B \-xx \-\-usb\fR
\- Adds vendor:chip id.
.TP
.B \-xx \-w\fR,\fB \-W\fR
\- Adds wind chill, heat index, and dew point if any of these are available.
.TP
.B \-xxx \-A\fR
\- Adds (if available and/or relevant) \fBvendor:\fR item, which shows 
specific vendor [product] information.

\- Adds, if present, serial number.
.TP
.B \-xxx \-B\fR
\- Adds battery chemistry (e.g. \fBLi\-ion\fR), cycles (NOTE: there appears to
be a problem with the Linux kernel obtaining the cycle count, so this almost
always shows \fB0\fR. There's nothing that can be done about this glitch, the
data is simply not available as of 2018\-04\-03), location (only available from
\fBdmidecode\fR derived output).

\- Adds attached device \fBrechargeable: [yes|no]\fR information. 
.TP
.B \-xxx \-C\fR
\- Adds \fBboost: [enabled|disabled]\fR if detected, aka \fBturbo\fR. Not all CPUs 
have this feature.
.TP
.B \-xxx \-D\fR
\- Adds disk firmware revision number (if available).

\- Adds disk partition scheme (in most cases), e.g. \fBscheme: GPT\fR. Currently not 
able to detect all schemes, but handles the most common, e.g. \fBGPT\fR or \fBMBR\fR.

\- Adds disk rotation speed (in some but not all cases), e.g. \fBrotation: 7200 rpm\fR. 
Only appears if detected (SSD drives do not have rotation speeds, for example). If none 
found, nothing shows. Not all disks report this speed, so even if they are spinnning,
no data will show.
.TP
.B \-xxx \-G\fR
\- Adds (if available and/or relevant) \fBvendor:\fR item, which shows 
specific vendor [product] information.

\- Adds (if available) \fBcompositor:\fR version \fBv:\fR.
.TP
.B \-xxx \-I\fR
\- For \fBShell:\fR adds \fB(su|sudo|login)\fR to shell name if present.

\- For \fBrunning in:\fR adds \fB(SSH)\fR to parent, if present. SSH detection
uses the \fBwho am i\fR test.
.TP
.B \-xxx \-m\fR
\- Adds memory bus width: primary bus width, and if present, total width. e.g.
\fBbus width: 64 bit (total: 72 bits)\fR. Note that total / data widths are mixed up
sometimes in dmidecode output, so inxi will take the larger value as the total if
present. If no total width data is found, then inxi will not show that item.

\- Adds device Type Detail, e.g. \fBdetail: DDR3 (Synchronous)\fR.

\- Adds, if present, memory module voltage. Only some systems will have this
data available.

\- Adds device serial number.
.TP
.B \-xxx \-N\fR
\- Adds, if present, serial number.
.TP
.B \-xxx \-R\fR
\- md\-raid: Adds system mdraid support types (kernel support, read ahead, RAID events)

\- zfs\-raid: Adds portion allocated (used) by RAID array/device.

\- Hardware RAID: Adds rev, ports, and (if available and/or relevant) 
\fBvendor:\fR item, which shows specific vendor [product] information.
.TP
.B \-xxx \-S\fR
\- Adds, if in X, or with \fB--display\fR, bar/dock/panel/tray items 
(\fBinfo\fR). If none found, shows nothing. Supports desktop items like gnome\-panel,
lxpanel, xfce4\-panel, lxqt\-panel, tint2, cairo-dock, trayer, and many others. 

\- Adds (if present), window manager (\fBwm\fR) version number.

\- Adds (if present), display manager (\fBdm\fR) version number.
.TP
.B \-xxx \-\-usb\fR
\- Adds, if present, serial number for non hub devices.

\- Adds \fBinterfaces:\fR for non hub devices.
.TP
.B \-xxx \-w\fR,\fB \-W\fR
\- Adds location (city state country), altitude, weather observation time.

.SH ADMIN EXTRA DATA OPTIONS
These options are triggered with \fB\-\-admin\fR or \fB\-a\fR. Admin options are 
advanced output options, and are more technical, and mostly of interest to system 
administrators or other machine admins. 
The \fB\-\-admin\fR option only has to be used once, and will trigger the following features.
.TP
.B \-a \-C\fR
\- Adds CPU family, model\-id, and stepping (replaces \fBrev\fR of \fB\-Cx\fR). 
Format is \fBhexadecimal (decimal)\fR if greater than 9, otherwise \fBhexadecimal\fR. 

\- Adds CPU microcode. Format is \fBhexadecimal\fR.

\- Adds CPU Vulnerabilities (bugs) as known by your current kernel. Lists by
\fBType: ... (status|mitigation): ....\fR for systems that support this feature 
(Linux kernel 4.14 or newer, or patched older kernels).

.SH ADVANCED OPTIONS

.TP
.B \-\-alt 40\fR
Bypass \fBPerl\fR as a downloader option. Priority is: Perl (HTTP::Tiny),
Curl, Wget, Fetch, (OpenBSD only) ftp.

.TP
.B \-\-alt 41\fR
Bypass \fBCurl\fR as a downloader option. Priority is: Perl (HTTP::Tiny),
Curl, Wget, Fetch, (OpenBSD only) ftp.

.TP
.B \-\-alt 42\fR
Bypass \fBFetch\fR as a downloader option. Priority is: Perl (HTTP::Tiny),
Curl, Wget, Fetch, (OpenBSD only) ftp.

.TP
.B \-\-alt 43\fR
Bypass \fBWget\fR as a downloader option. Priority is: Perl (HTTP::Tiny),
Curl, Wget, Fetch, OpenBSD only: ftp

.TP
.B \-\-alt 44\fR
Bypass \fBCurl\fR, \fBFetch\fR, and \fBWget\fR as downloader options. This
basically forces the downloader selection to use \fBPerl 5.x\fR \fBHTTP::Tiny\fR,
which is generally slower than \fBCurl\fR or \fBWget\fR but it may help bypass
issues with downloading.

.TP
.B \-\-display [:<integer>]\fR
Will try to get display data out of X (does not usually work as root user).
Default gets display info from display \fB:0\fR. If you use the format
\fB\-\-display :1\fR then it would get it from display \fB1\fR instead,
or any display you specify.

Note that in some cases, \fB\-\-display\fR will cause inxi to hang endlessly when
running the option in console with Intel graphics. The situation regarding
other free drivers such as nouveau/ATI is currently unknown. It may be that
this is a bug with the Intel graphics driver \- more information is required.

You can test this easily by running the following command out of X/display server:
\fBglxinfo \-display :0\fR

If it hangs, \fB\-\-display\fR will not work.

.TP
.B \-\-dmidecode\fR
Force use of \fBdmidecode\fR. This will override \fB/sys\fR data in some lines,
e.g. \fB\-M\fR or \fB\-B\fR.

.TP
.B \-\-downloader [curl|fetch|perl|wget]\fR
Force inxi to use Curl, Fetch, Perl, or Wget for downloads.

.TP
.B \-\-host\fR
Turns on hostname in System line. Overrides inxi config file value (if set):

\fBSHOW_HOST='false'\fR

.TP
.B \-\-indent\-min [integer]\fR
Overrides default indent minimum value. This is the value that makes inxi change from
wrapped line starters [like \fBInfo\fR] to non wrapped. If less than \fB80\fR,
no wrapping will occur. Overrides internal default value and user configuration value:

\fBINDENT_MIN=85\fR

.TP
.B \-\-limit [\-1 \- x]\fR
Raise or lower max output limit of IP addresses for \fB\-i\fR. \fB\-1\fR removes limit.

.TP
.B \-\-man\fR
Updates / installs man page with \fB\-U\fR if \fBpinxi\fR or using \fB\-U 3\fR dev branch.
(Only active if \fB\-U\fR is is not disabled by maintainers).

.TP
.B \-\-no\-host\fR
Turns off hostname in System line. Useful, in combination with \fB\-z\fR,
for anonymizing inxi output for posting on forums or IRC. Same as
configuration value:

\fBSHOW_HOST='false'\fR

.TP
.B \-\-no\-man\fR
Disables man page install with \fB\-U\fR for master and active development branches.
(Only active if \fB\-U\fR is is not disabled by maintainers).

.TP
.B \-\-no\-ssl\fR
Skip SSL certificate checks for all downloader actions (\fB\-U\fR, \fB\-w\fR,
\fB\-W\fR, \fB\-i\fR). Use if your system does not have current SSL certificate
lists, or if you have problems making a connection for any reason. Works with
\fBWget\fR, \fBCurl\fR, and \fBFetch\fR only.

.TP
.B \-\-output [json|screen|xml]\fR
Change data output type. Requires \-\-output\-file if not fBscreen\fR.

.TP
.B \-\-output\-file [full path to output file|print]\fR
The given directory path must exist. The directory path given must exist,
The \fBprint\fR options prints to stdout.
Required for non\-screen \fB\-\-output\fR formats (json|xml).

.TP
.B \-\-sleep [0\-x.x]\fR
Usually in decimals. Change CPU sleep time for \fB\-C\fR (current: \fB\0.35\fR).
Sleep is used to let the system catch up and show a more accurate CPU use. Example:

\fBinxi \-Cxxx \-\-sleep 0.15\fR

Overrides default internal value and user configuration value:

\fBCPU_SLEEP=0.25\fR

.TP
.B \-\-usb\-sys\fR
Forces the USB data generator to use \fB/sys\fR as data source 
instead of \fBlsusb\fR.

.TP
.B \-\-usb\-tool\fR
Forces the USB data generator to use \fBlsusb\fR as data source. Overrides 
\fBUSB_SYS\fR in user configuration file(s).

.TP
.B \-\-wm\fR
Force \fBSystem\fR item \fBwm\fR to use \fBwmctrl\fR as data source, 
override default \fBps\fR source.

.SH DEBUGGING OPTIONS

.TP
.B \-\-debug [1\-3]\fR
\- On screen debugger output. Output varies depending on current needs
Usually nothing changes.

.TP
.B \-\-debug 10\fR
\- Basic logging. Check \fB$XDG_DATA_HOME/inxi/inxi.log\fR or
\fB$HOME/.local/share/inxi/inxi.log\fR or \fB$HOME/.inxi/inxi.log\fR.

.TP
.B \-\-debug 11\fR
\- Full file/system info logging.

.TP
.B \-\-debug 20\fR
Creates a tar.gz file of system data and collects the inxi output
in a file.

* tree traversal data file(s) read from \fB/proc\fR and \fB/sys\fR, and 
other system data.

* xorg conf and log data, xrandr, xprop, xdpyinfo, glxinfo etc.

* data from dev, disks, partitions, etc.

.TP
.B \-\-debug 21\fR
Automatically uploads debugger data tar.gz file to \fIftp.techpatterns.com\fR,
then removes the debug data directory, but leaves the debug tar.gz file.
See \fB\-\-ftp\fR for uploading to alternate locations.

.TP
.B \-\-debug 22\fR
Automatically uploads debugger data tar.gz file to \fIftp.techpatterns.com\fR, then
removes the debug data directory and the tar.gz file.
See \fB\-\-ftp\fR for uploading to alternate locations.

.TP
.B \-\-ftp [ftp.yoursite.com/incoming]\fR
For alternate ftp upload locations: Example:

\fBinxi \-\-ftp \fIftp.yourserver.com/incoming\fB \-\-debug 21\fR

.TP
.B \-\-proc\fR
Force debugger to parse \fB/proc\fR directory data when run as root. Normally this is
disabled due to unpredictable data in /proc tree. Only used with \fB\-\-debug 2x\fR.

.SH SUPPORTED IRC CLIENTS
BitchX, Gaim/Pidgin, ircII, Irssi, Konversation, Kopete, KSirc, KVIrc, Weechat,
and Xchat. Plus any others that are capable of displaying either built\-in or external
script output.

.SH RUNNING IN IRC CLIENT
To trigger inxi output in your IRC client, pick the appropriate method from the
list below:
.TP
.B Hexchat, XChat, Irssi
\fR(and many other IRC clients)
.B /exec \-o inxi \fR[\fBoptions\fR]
If you don't include the \fB\-o\fR, only you will see the output on your local
IRC client.
.TP
.B Konversation
.B /cmd inxi
\fR[\fBoptions\fR]

To run inxi in Konversation as a native script if your distribution or inxi package
hasn't already done this for you, create this symbolic link:

KDE 4:
.B ln \-s /usr/local/bin/inxi /usr/share/kde4/apps/konversation/scripts/inxi

KDE 5:
.B ln \-s /usr/local/bin/inxi /usr/share/konversation/scripts/inxi

If inxi is somewhere else, change the path \fB/usr/local/bin\fR to wherever it
is located.

If you are using KDE/QT 5, then you may also need to add the following to get
the Konversation \fR/inxi\fR command to work:

.B ln \-s /usr/share/konversation /usr/share/apps/

Then you can start inxi directly, like this:

.B /inxi
\fR[\fBoptions\fR]
.TP
.B WeeChat
.B NEW: /exec \-o inxi
\fR[\fBoptions\fR]

.B OLD: /shell \-o inxi
\fR[\fBoptions\fR]

Newer (2014 and later) WeeChats work pretty much the same now as other console
IRC clients, with \fB/exec \-o inxi \fR[\fBoptions\fR]. Newer WeeChats
have dropped the \fB\-curses\fR part of their program name, i.e.:
\fBweechat\fR instead of \fBweechat\-curses\fR.

.SH CONFIGURATION FILE
inxi will read its configuration/initialization files in the
following order:

\fB/etc/inxi.conf\fR contains the default configurations. These can be overridden
by user configurations found in one of the following locations (inxi will
store its config file using the following precedence:
if \fB$XDG_CONFIG_HOME\fR is not empty, it will go there, else if
\fB$HOME/.conf/inxi.conf\fR exists, it will go there, and as a last default,
the legacy location is used), i.e.:

\fB$XDG_CONFIG_HOME/inxi.conf\fR > \fB$HOME/.conf/inxi.conf\fR >
\fB$HOME/.inxi/inxi.conf\fR

.SH CONFIGURATION OPTIONS

See the documentation page for more complete information on how to set
these up, and for a complete list of options:

.I https://smxi.org/docs/inxi\-configuration.htm
.TP
.B Basic Options
Here's a brief overview of the basic options you are likely to want to use:

\fBCOLS_MAX_CONSOLE\fR The max display column width on terminal.

\fBCOLS_MAX_IRC\fR The max display column width on IRC clients.

\fBCOLS_MAX_NO_DISPLAY\fR The max display column width in console, out of GUI desktop.

\fBCPU_SLEEP\fR Decimal value \fB0\fR or more. Default is usually around \fB0.35\fR
seconds. Time that inxi will 'sleep' before getting CPU speed data, so that it
reflects actual system state.

\fBDOWNLOADER\fR Sets default inxi downloader: curl, fetch, ftp, perl, wget.
See \fB\-\-recommends\fR output for more information on downloaders and Perl downloaders.

\fBFILTER_STRING\fR Default \fB<filter>\fR. Any string you prefer to see instead
for filtered values.

\fBINDENT_MIN\fR The point where the line starter wrapping to its own line happens.
Overrides default. See \fB\-\-indent\-min\fR. If \fB80\fR or less, wrap will never happen.

\fBLIMIT\fR Overrides default of \fB10\fR IP addresses per IF. This is only of interest
to sys admins running servers with many IP addresses.

\fBPS_COUNT\fR The default number of items showing per \fB\-t\fR type, \fBm\fR or 
\fBc\fR. Default is 5.

\fBSENSORS_CPU_NO\fR In cases of ambiguous temp1/temp2 (inxi can't figure out which
is the CPU), forces sensors to use  either value 1 or 2 as CPU temperature. See the
above configuration page on smxi.org for full info.

\fBSEP2_CONSOLE\fR Replaces default key / value separator of '\fB:\fR'.

\fBUSB_SYS\fR Forces all USB data to use \fB/sys\fR instead of \fBlsusb\fR.

\fBWEATHER_UNIT\fR Values: [\fBc\fR|\fBf\fR|\fBcf\fR|\fBfc\fR]. Same as \fB\-\-weather\-unit\fR.

.TP
.B Color Options
It's best to use the \fB\-c [94\-99]\fR color selector tool to set the following values
because it will correctly update the configuration file and remove any invalid
or conflicting items, but if you prefer to create your own configuration files,
here are the options. All take the integer value from the options available in
\fB\-c 94\-99\fR.

NOTE: All default and configuration file set color values are removed when output is 
piped or redirected. You must use the explicit \fB\-c <color number>\fR option 
if you want colors to be present in the piped/redirected output (creating a PDF for
example).

\fBCONSOLE_COLOR_SCHEME\fR The color scheme for console output (not in X/Wayland).

\fBGLOBAL_COLOR_SCHEME\fR Overrides all other color schemes.

\fBIRC_COLOR_SCHEME\fR Desktop X/Wayland IRC CLI color scheme.

\fBIRC_CONS_COLOR_SCHEME\fR Out of X/Wayland, IRC CLI color scheme.

\fBIRC_X_TERM_COLOR_SCHEME\fR In X/Wayland IRC client terminal color scheme.

\fBVIRT_TERM_COLOR_SCHEME\fR Color scheme for virtual terminal output (in X/Wayland).

.SH BUGS
Please report bugs using the following resources.

You may be asked to run the inxi debugger tool (see \fB\-\-debug 21/22\fR), which will 
upload a data dump of system files for use in debugging inxi. These data dumps are 
very important since they provide us with all the real system data inxi uses to parse 
out its report.
.TP
.B Issue Report
File an issue report:
.I https://github.com/smxi/inxi/issues
.TP
.B Developer Forums
Post on inxi developer forums:
.I https://techpatterns.com/forums/forum\-32.html
.TP
.B IRC irc.oftc.net#smxi
You can also visit
.I irc.oftc.net
\fRchannel:\fI #smxi\fR to post issues.

.SH HOMEPAGE
.I  https://github.com/smxi/inxi
.I  https://smxi.org/

.SH  AUTHOR AND CONTRIBUTORS TO CODE

.B inxi
is a fork of \fBlocsmif\fR's very clever \fBinfobash\fR script.

Original infobash author and copyright holder:
Copyright (C) 2005\-2007  Michiel de Boer aka locsmif

inxi version: Copyright (C) 2008\-18 Harald Hope

This man page was originally created by Gordon Spencer (aka aus9) and is
maintained by Harald Hope (aka h2 or TechAdmin).

Initial CPU logic, konversation version logic, occasional maintenance fixes,
and the initial xiin.py tool for /sys parsing (obsolete, but still very much
appreciated for all the valuable debugger data it helped generate): Scott Rogers

Further fixes (listed as known):

Horst Tritremmel <hjt at sidux.com>

Steven Barrett (aka: damentz) \- USB audio patch; swap percent used patch.

Jarett.Stevens \- \fBdmidecode \-M\fR patch for older systems with no \fB/sys\fR.

.SH SPECIAL THANKS TO THE FOLLOWING

The nice people at irc.oftc.net channels #linux\-smokers\-club and #smxi,
who  all really have to be considered to be co\-developers because of their
non\-stop enthusiasm and willingness to provide real\-time testing and debugging
of inxi development.

Siduction forum members, who have helped get some features working by providing
a large number of datasets that have revealed possible variations, particularly for the
RAM \fB\-m\fR option.

AntiX users and admins, who have helped greatly with testing and debugging,
particularly for the 3.0.0 release.

ArcherSeven (Max), Brett Bohnenkamper (aka KittyKatt), and Iotaka, who always 
manage to find the weirdest or most extreme hardware and setups that help make 
inxi much more robust.

For the vastly underrated skill of output error/glitch catching, Pete Haddow. His
patience and focus in going through inxi repeatedly to find errors and inconsistencies 
is much appreciated.

All the inxi package maintainers, distro support people, forum moderators,
and in particular, sys admins with their particular issues, which almost always
help make inxi better, and any others who contribute ideas, suggestions, and patches.

Without a wide range of diverse Linux kernel\-based Free Desktop systems to test
on, we could never have gotten inxi to be as reliable and solid as it's turning
out to be.

And of course, a big thanks to locsmif, who figured out a lot of the core methods,
logic, and tricks originally used in inxi Gawk/Bash.
