name: inxi
version: 3.3.04-1
summary: inxi - a command line system information tool
description: |
  inxi is a full featured CLI system information tool.
  It is available in most Linux distribution repositories,
  and does its best to support the BSDs.
confinement: devmode
base: core18
grade: stable

parts:
  inxi:
    plugin: dump
    source: https://github.com/smxi/inxi/archive/$SNAPCRAFT_PROJECT_VERSION.tar.gz
    stage-packages:
      - pciutils
      - procps
      - libxml-dumper-perl
      - libcpanel-json-xs-perl
      - libjson-xs-perl
      - wget
      - dmidecode
      - file
      - dnsutils
      - hddtemp
      - iproute2
      - sudo
      - kmod
      - lm-sensors
      - mesa-utils
      - tree
      - usbutils
      - x11-utils
      - x11-xserver-utils
      - libatm1
      - libmagic-dev
      - perl-base
      - libfile-find-rule-perl-perl
      - locales-all

apps:
  inxi:
    environment:
      LOCPATH: "$SNAP/usr/lib/locale"
      PERL5LIB:  "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl-base/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl5/5.26/:$SNAP/usr/share/perl5/:$SNAP/usr/share/perl/5.26.1/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl/5.26/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl/5.26.1/"
      HOME: "$SNAP_USER_COMMON"
    command: perl $SNAP/inxi

